import placeholder from "./placeholder.jpeg";

export const resturants = [
  {
    name: "ABs",
    rating: 3,
    cuisines: ["Indian", "Chinese"],
    imgSrc: placeholder,
    promoted: false,
  },
  {
    name: "Berbeque",
    rating: 3,
    cuisines: ["Indian", "Chinese", "Continental"],
    imgSrc: placeholder,
    promoted: true,
  },
  {
    name: "Dominos",
    rating: 3,
    cuisines: ["Indian", "Italian"],
    imgSrc: placeholder,
    promoted: false,
  },
  {
    name: "Pizzahut",
    rating: 2,
    cuisines: ["Indian", "Chinese"],
    imgSrc: placeholder,
    promoted: false,
  },
  {
    name: "ABs",
    rating: 2,
    cuisines: ["Indian", "Chinese"],
    imgSrc: placeholder,
    promoted: false,
  },
  {
    name: "Berbeque",
    rating: 2,
    cuisines: ["Indian", "Chinese", "Continental"],
    imgSrc: placeholder,
  },
  {
    name: "Dominos",
    rating: 2.5,
    cuisines: ["Indian", "Italian"],
    imgSrc: placeholder,
    promoted: false,
  },
  {
    name: "Pizzahut",
    rating: 2.5,
    cuisines: ["Indian", "Chinese"],
    imgSrc: placeholder,
    promoted: false,
  },
  {
    name: "ABs",
    rating: 2.5,
    cuisines: ["Indian", "Chinese"],
    imgSrc: placeholder,
    promoted: false,
  },
  {
    name: "Berbeque",
    rating: 4,
    cuisines: ["Indian", "Chinese", "Continental"],
    imgSrc: placeholder,
    promoted: false,
  },
  {
    name: "Dominos",
    rating: 4,
    cuisines: ["Indian", "Italian"],
    imgSrc: placeholder,
    promoted: true,
  },
  {
    name: "Pizzahut",
    rating: 4,
    cuisines: ["Indian", "Chinese"],
    imgSrc: placeholder,
    promoted: false,
  },
];
